#!/bin/bash

# Make sure we are in the script directory
ScriptDIR=$(cd `dirname $0` && pwd)
if [ $ScriptDIR != $PWD ]; then
   echo "Ce script doit être executé depuis son dossier" 1>&2
   exit
fi

#On récupère le nombre de sessions actives de Yane
C=`sudo ./yane  -l | wc -l`

#On vérifie qu'aucune session n'est déjà lancée
if [ "$C" != "0" ] ; then
  echo "Une session est déjà lancée pour la fermer executez la commande:"
  echo "   STOP"
  exit

else
  #On copie les scripts dans le dossier partagé du Docker correspondant
  cp ./scripts/serveur-web ./files/serveur-web/var/scripts/init
  cp ./scripts/serveur-dns ./files/serveur-dns/etc/scripts/init
  cp ./scripts/routeur-services-reseaux ./files/routeur-services-reseaux/etc/scripts/init
  cp ./scripts/routeur-services ./files/routeur-services/etc/scripts/init
  cp ./scripts/R1 ./files/R1/etc/scripts/init
  cp ./scripts/R2 ./files/R2/etc/scripts/init
  cp ./scripts/routeur-fai ./files/routeur-fai/etc/scripts/init
  cp ./scripts/box-user1 ./files/box-user1/etc/scripts/init
  cp ./scripts/box-user2 ./files/box-user2/etc/scripts/init
  cp ./scripts/serveur-web-user2 ./files/serveur-web-user2/var/scripts/init
  echo 'Chargement des VM..'
  #On lance Yane
  sudo ./yane > /dev/null
  exit
fi
