#!/bin/bash

## Make sure we are in the script directory
ScriptDIR=$(cd `dirname $0` && pwd)
if [ $ScriptDIR != $PWD ]; then
   echo "Ce script doit être executé depuis son dossier" 1>&2
   exit
fi

#On récupère le nombre de sessions actives de Yane
C=`sudo ./yane  -l | wc -l`

if [ "$C" == "0" ] ; then
  echo "Aucune session n'est lancée pour en lancer une executez :"
  echo "   START"

elif [ "$C" -gt "1" ] ; then
  echo "Trop de sessions ouvertes !! "
  echo "Pour voir les ID de session :"
  echo "   sudo yane -l"
  echo "Pour forcer la fermuture d'une session :"
  echo "   sudo yane -s <ID SESSION> -k"

else

  rm ./files/serveur-web/var/scripts/init
  rm ./files/serveur-dns/etc/scripts/init
  rm ./files/routeur-services-reseaux/etc/scripts/init
  rm ./files/routeur-services/etc/scripts/init
  rm ./files/R1/etc/scripts/init
  rm ./files/R2/etc/scripts/init
  rm ./files/routeur-fai/etc/scripts/init
  rm ./files/box-user1/etc/scripts/init
  rm ./files/box-user2/etc/scripts/init
  rm ./files/serveur-web-user2/var/scripts/init
  sudo ./yane -k > /dev/null 2> /dev/null
  #On supprime tout les namespaces
  sudo ip -all netns delete > /dev/null

  #On supprime tout les dockers
  if [ `sudo docker ps -a -q | wc -l` != 0 ] ; then
    sudo docker stop `sudo docker ps -a -q` > /dev/null
    sudo docker rm `sudo docker ps -a -q` > /dev/null
  fi
fi
